CREATE TABLE `cust_ledger_entries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entry_no` int(11) NOT NULL,
  `transaction_no` int(11) DEFAULT NULL,
  `customer_no` varchar(20) DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `document_date` date DEFAULT NULL,
  `document_type` varchar(255) DEFAULT NULL,
  `document_no` varchar(20) DEFAULT NULL,
  `external_document_no` varchar(50) DEFAULT NULL,
  `document_posting_date` date DEFAULT NULL,
  `salesperson_code` varchar(20) DEFAULT NULL,
  `source_code` varchar(10) DEFAULT NULL,
  `open` tinyint(1) DEFAULT NULL,
  `document_status` varchar(255) DEFAULT NULL,
  `payment_method_code` varchar(10) DEFAULT NULL,
  `payment_terms_code` varchar(10) DEFAULT NULL,
  `payment_doc_due_date` date DEFAULT NULL,
  `amount` decimal(11,3) DEFAULT NULL,
  `debit_amount` decimal(11,3) DEFAULT NULL,
  `credit_amount` decimal(11,3) DEFAULT NULL,
  `remaining_amount` decimal(11,3) DEFAULT NULL,
  `amount_lcy` decimal(11,3) DEFAULT NULL,
  `debit_amount_lcy` decimal(11,3) DEFAULT NULL,
  `credit_amount_lcy` decimal(11,3) DEFAULT NULL,
  `remaining_amt_lcy` decimal(11,3) DEFAULT NULL,
  `original_amt_lcy` decimal(11,3) DEFAULT NULL,
  `sales_lcy` decimal(11,3) DEFAULT NULL,
  `customer_entry_comment` varchar(80) DEFAULT NULL,
  `closed_at_date` date DEFAULT NULL,
  `source_posting_date` date DEFAULT NULL,
  `urban_invoice` tinyint(1) DEFAULT NULL,
  `urban_credit_memo` tinyint(1) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `days_payment_delay` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cust_ledger_entries_entry_no_unique` (`entry_no`),
  KEY `cust_ledger_entries_document_no_document_status_index` (`document_no`,`document_status`) USING BTREE,
  KEY `cust_ledger_entries_entry_no_index` (`entry_no`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2085889 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `customers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `no` varchar(20) DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `face_accounting_department` varchar(255) DEFAULT NULL,
  `face_managing_department` varchar(255) DEFAULT NULL,
  `face_processing_department` varchar(255) DEFAULT NULL,
  `balance_lcy` decimal(8,2) DEFAULT 0.00,
  `credit_limit_lcy` decimal(8,2) DEFAULT NULL,
  `salesperson_code` varchar(255) DEFAULT NULL,
  `previous_salesperson` varchar(255) DEFAULT NULL,
  `invoice_sent_by_email` tinyint(1) DEFAULT NULL,
  `document_sending_profile` varchar(255) DEFAULT NULL,
  `total_sales_current_year` decimal(11,3) DEFAULT NULL,
  `total_sales_previous_year` decimal(11,3) DEFAULT NULL,
  `total_sales_two_years_ago` decimal(11,3) DEFAULT NULL,
  `total_sales_older_than_three_years_ago` decimal(11,3) DEFAULT NULL,
  `total_sales_customer` decimal(11,3) DEFAULT NULL,
  `totalsales2` decimal(11,3) DEFAULT NULL,
  `total_sales` decimal(11,3) DEFAULT NULL,
  `totalsales3` decimal(11,3) DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `email_invoicing` varchar(255) DEFAULT NULL,
  `afnef_registration_date` datetime DEFAULT NULL,
  `inactive` tinyint(1) DEFAULT NULL,
  `average_days_payment_delay` decimal(8,2) DEFAULT NULL,
  `external_customer_no` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `post_code` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `county` varchar(255) DEFAULT NULL,
  `country_region_code` varchar(255) DEFAULT NULL,
  `contact` varchar(255) DEFAULT NULL,
  `default_contact_id` bigint(20) unsigned DEFAULT NULL,
  `telex_no` varchar(255) DEFAULT NULL,
  `phone_no` varchar(255) DEFAULT NULL,
  `phone_no_2` varchar(100) DEFAULT NULL,
  `e_mail` varchar(255) DEFAULT NULL,
  `fax_no` varchar(255) DEFAULT NULL,
  `vat_registration_no` varchar(255) DEFAULT NULL,
  `payment_method_code` varchar(255) DEFAULT NULL,
  `payment_terms_code` varchar(255) DEFAULT NULL,
  `requires_job_reference` tinyint(1) DEFAULT 0,
  `gen_bus_posting_group` varchar(255) DEFAULT NULL,
  `vat_bus_posting_group` varchar(255) DEFAULT NULL,
  `customer_posting_group` varchar(255) DEFAULT NULL,
  `media_das_demora_pago` varchar(255) DEFAULT NULL,
  `ordersblocked` tinyint(1) NOT NULL DEFAULT 0,
  `send_via_voxel` varchar(20) NOT NULL DEFAULT 'No',
  `sector` varchar(255) DEFAULT NULL,
  `sector_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `last_purchase_date` date DEFAULT NULL,
  `salesperson_status` varchar(255) DEFAULT NULL,
  `sync_status` tinyint(4) NOT NULL DEFAULT 0,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `no` (`no`),
  KEY `customers_no_index` (`no`),
  KEY `customers_vat_registration_no_IDX` (`vat_registration_no`) USING BTREE,
  KEY `customers_vat_registration_no_index` (`vat_registration_no`)
) ENGINE=InnoDB AUTO_INCREMENT=118711 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `item_ledger_entries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entry_no` int(11) NOT NULL,
  `entry_type` varchar(255) DEFAULT NULL,
  `item_no` varchar(20) DEFAULT NULL,
  `cross_reference_no` varchar(20) DEFAULT NULL,
  `lot_no` varchar(20) DEFAULT NULL,
  `item_category_code` varchar(20) DEFAULT NULL,
  `product_group_code` varchar(10) DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `expiration_date` date DEFAULT NULL,
  `warranty_date` date DEFAULT NULL,
  `document_date` date DEFAULT NULL,
  `document_no` varchar(20) DEFAULT NULL,
  `document_type` varchar(255) DEFAULT NULL,
  `location_code` varchar(10) DEFAULT NULL,
  `job_no` varchar(20) DEFAULT NULL,
  `job_task_no` varchar(20) DEFAULT NULL,
  `open` tinyint(1) DEFAULT NULL,
  `quantity` decimal(11,3) DEFAULT NULL,
  `unit_of_measure_code` varchar(10) DEFAULT NULL,
  `qty_per_unit_of_measure` decimal(11,3) DEFAULT NULL,
  `remaining_quantity` decimal(11,3) DEFAULT NULL,
  `invoiced_quantity` decimal(11,3) DEFAULT NULL,
  `dimension_set_id` int(11) DEFAULT NULL,
  `source_no` varchar(20) DEFAULT NULL,
  `cost_amount_expected` decimal(11,3) DEFAULT NULL,
  `cost_amount_actual` decimal(11,3) DEFAULT NULL,
  `cost_amount_non_invtbl` decimal(11,3) DEFAULT NULL,
  `purchase_amount_expected` decimal(11,3) DEFAULT NULL,
  `purchase_amount_actual` decimal(11,3) DEFAULT NULL,
  `sales_amount_expected` decimal(11,3) DEFAULT NULL,
  `sales_amount_actual` decimal(11,3) DEFAULT NULL,
  `item_description` varchar(50) DEFAULT NULL,
  `auxiliaryindex1` varchar(20) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `new_item_ledger_entries_entry_no_auxiliaryindex1_index` (`entry_no`,`auxiliaryindex1`)
) ENGINE=InnoDB AUTO_INCREMENT=1320174 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `products` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `no` varchar(20) NOT NULL DEFAULT '',
  `marketing_code` varchar(255) DEFAULT NULL,
  `description` varchar(50) NOT NULL DEFAULT '',
  `description_2` varchar(255) DEFAULT NULL,
  `search_description` varchar(255) DEFAULT NULL,
  `auto_reg_lm_sales` tinyint(1) NOT NULL DEFAULT 0,
  `sicom_integration` tinyint(1) NOT NULL,
  `app_integration` tinyint(1) NOT NULL DEFAULT 0,
  `ecommerce_integration` tinyint(1) NOT NULL,
  `type` varchar(255) NOT NULL DEFAULT '',
  `blocked` tinyint(1) NOT NULL,
  `registration_date` date NOT NULL,
  `base_unit_of_measure` varchar(10) NOT NULL DEFAULT '',
  `abc_classification` varchar(255) DEFAULT NULL,
  `nav4_family_code` varchar(20) NOT NULL DEFAULT '',
  `product_type_code` varchar(20) NOT NULL DEFAULT '',
  `product_classification_code` varchar(20) NOT NULL DEFAULT '',
  `product_commission_type_code` varchar(10) NOT NULL DEFAULT '',
  `measurement` decimal(11,3) NOT NULL,
  `shelf_no` varchar(10) NOT NULL DEFAULT '',
  `inventory` decimal(11,3) NOT NULL,
  `unit_cost` decimal(11,3) NOT NULL,
  `last_direct_cost` decimal(8,2) NOT NULL,
  `cost_is_adjusted` tinyint(1) NOT NULL DEFAULT 0,
  `vat_prod_posting_group` varchar(20) NOT NULL DEFAULT '',
  `unit_price` decimal(11,3) NOT NULL,
  `allow_invoice_disc` tinyint(1) NOT NULL,
  `sales_unit_of_measure` varchar(10) NOT NULL DEFAULT '',
  `replenishment_system` varchar(255) NOT NULL DEFAULT '',
  `lead_time_calculation` varchar(255) NOT NULL DEFAULT '',
  `vendor_no` varchar(20) NOT NULL DEFAULT '',
  `last_date_modified` date NOT NULL,
  `gtin` varchar(14) NOT NULL DEFAULT '',
  `on_request` tinyint(1) NOT NULL,
  `discontinued` tinyint(1) NOT NULL,
  `stockout` tinyint(1) NOT NULL DEFAULT 0,
  `net_weight` decimal(11,3) NOT NULL,
  `gross_weight` decimal(11,3) NOT NULL,
  `height` decimal(11,3) NOT NULL,
  `width` decimal(11,3) NOT NULL,
  `length` decimal(11,3) NOT NULL,
  `unit_volume` decimal(11,3) NOT NULL,
  `hazardous_material` tinyint(1) NOT NULL,
  `adr` tinyint(1) NOT NULL,
  `no_of_packages` decimal(11,3) NOT NULL,
  `promotional_product` tinyint(1) NOT NULL,
  `web_product` tinyint(1) NOT NULL,
  `kit` tinyint(1) DEFAULT NULL,
  `commercial_division_code` varchar(255) DEFAULT NULL,
  `product_family_code` varchar(255) DEFAULT NULL,
  `product_subfamily_code` varchar(255) DEFAULT NULL,
  `production_type_code` varchar(255) DEFAULT NULL,
  `sicom_stock_management` tinyint(1) NOT NULL DEFAULT 0,
  `customizable` tinyint(1) NOT NULL DEFAULT 0,
  `over_2_40m` tinyint(1) NOT NULL DEFAULT 0,
  `raw_material_no` varchar(20) DEFAULT NULL,
  `assembly_bom` tinyint(1) DEFAULT NULL,
  `costing_method` varchar(255) DEFAULT NULL,
  `in_settlement` tinyint(1) NOT NULL DEFAULT 0,
  `gen_prod_posting_group` varchar(20) DEFAULT NULL,
  `manufacturing_policy` varchar(255) DEFAULT NULL,
  `overhead_rate` decimal(8,2) DEFAULT NULL,
  `production_bom_no` varchar(20) DEFAULT NULL,
  `qty_on_purch_order` decimal(8,2) DEFAULT NULL,
  `qty_on_asm_component` decimal(8,2) DEFAULT NULL,
  `qty_on_assembly_order` decimal(8,2) DEFAULT NULL,
  `qty_on_component_lines` decimal(8,2) DEFAULT NULL,
  `qty_on_prod_order` decimal(8,2) DEFAULT NULL,
  `qty_on_sales_order` decimal(8,2) DEFAULT NULL,
  `routing_no` varchar(20) DEFAULT NULL,
  `standard_cost` decimal(8,2) DEFAULT NULL,
  `enliquidacion` tinyint(1) DEFAULT NULL,
  `minimum_order_quantity` decimal(8,2) DEFAULT NULL,
  `order_multiple` decimal(8,2) DEFAULT NULL,
  `season_end_month` varchar(255) DEFAULT NULL,
  `source_sku` varchar(20) DEFAULT NULL,
  `season_start_month` varchar(255) DEFAULT NULL,
  `sga_status` varchar(255) DEFAULT NULL,
  `sku_origen` varchar(20) DEFAULT NULL,
  `inventory_posting_group` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `item_category_code` varchar(255) NOT NULL,
  `bulky` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `products_no_index` (`no`),
  KEY `products_gtin_index` (`gtin`)
) ENGINE=InnoDB AUTO_INCREMENT=12087 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_order_headers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_type` varchar(255) NOT NULL,
  `no` varchar(255) NOT NULL,
  `buy_from_vendor_no` varchar(255) NOT NULL,
  `posting_date` date NOT NULL,
  `order_date` date NOT NULL,
  `status` varchar(255) NOT NULL,
  `lead_time_calculation` varchar(255) NOT NULL,
  `requested_receipt_date` date NOT NULL,
  `promised_receipt_date` date NOT NULL,
  `expected_receipt_date` date NOT NULL,
  `location_code` varchar(255) NOT NULL,
  `sga_status` varchar(255) NOT NULL,
  `sga_roc_status` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13645 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `purchase_order_lines` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_no` varchar(255) NOT NULL,
  `line_no` int(11) NOT NULL,
  `no` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `location_code` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `unit_of_measure_code` varchar(255) NOT NULL,
  `qty_to_receive` int(11) NOT NULL,
  `quantity_received` int(11) NOT NULL,
  `qty_to_invoice` int(11) NOT NULL,
  `quantity_invoiced` int(11) NOT NULL,
  `unit_cost_lcy` decimal(8,2) NOT NULL,
  `line_discount` decimal(8,2) NOT NULL,
  `line_discount_amount` decimal(8,2) NOT NULL,
  `line_amount` decimal(8,2) NOT NULL,
  `auxiliaryindex1` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=40319 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sales_invoice_headers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `no` varchar(20) DEFAULT NULL,
  `order_no` varchar(20) NOT NULL,
  `sell_to_customer_no` varchar(20) DEFAULT NULL,
  `sell_to_customer_name` varchar(100) DEFAULT NULL,
  `bill_to_customer_no` varchar(20) DEFAULT NULL,
  `vat_registration_no` varchar(255) DEFAULT NULL,
  `posting_date` timestamp NULL DEFAULT NULL,
  `payment_terms_code` varchar(10) DEFAULT NULL,
  `due_date` timestamp NULL DEFAULT NULL,
  `salesperson_code` varchar(20) DEFAULT NULL,
  `external_document_no` varchar(35) DEFAULT NULL,
  `payment_method_code` varchar(10) DEFAULT NULL,
  `vat_base_discount_percent` decimal(11,3) NOT NULL,
  `remaining_amount` decimal(11,3) NOT NULL,
  `invoice_discount_amount` decimal(11,3) NOT NULL,
  `document_freight` decimal(11,3) NOT NULL,
  `merch_points` decimal(11,3) NOT NULL,
  `gift_percentage` decimal(11,3) NOT NULL,
  `merch_generated` decimal(11,3) DEFAULT NULL,
  `merch_consumed` decimal(11,3) DEFAULT NULL,
  `merch_amount` decimal(11,3) DEFAULT NULL,
  `work_description` varchar(50) DEFAULT NULL,
  `ship_to_name` varchar(255) DEFAULT NULL,
  `ship_to_address` varchar(255) DEFAULT NULL,
  `ship_to_city` varchar(255) DEFAULT NULL,
  `ship_to_post_code` varchar(255) DEFAULT NULL,
  `ship_to_county` varchar(255) DEFAULT NULL,
  `currency_code` varchar(10) DEFAULT NULL,
  `amount` decimal(11,3) NOT NULL,
  `status` varchar(150) DEFAULT NULL,
  `sii_status` varchar(4) DEFAULT NULL,
  `observations` text DEFAULT NULL,
  `days_payment_delay` varchar(10) DEFAULT NULL,
  `amount_including_vat` decimal(11,3) DEFAULT NULL,
  `face_sending` varchar(50) DEFAULT NULL,
  `face_status` varchar(100) DEFAULT NULL,
  `closed_at_date` datetime DEFAULT NULL,
  `andorra_price_adjustment` decimal(8,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sales_invoice_headers_no_posting_date_salesperson_code_index` (`no`,`posting_date`,`salesperson_code`)
) ENGINE=InnoDB AUTO_INCREMENT=254186 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sales_invoice_lines` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_no` varchar(20) NOT NULL,
  `line_no` int(11) NOT NULL,
  `sell_to_customer_no` varchar(20) DEFAULT NULL,
  `no` varchar(20) DEFAULT NULL,
  `description` varchar(50) DEFAULT NULL,
  `quantity` decimal(11,3) DEFAULT NULL,
  `unit_price` decimal(11,3) DEFAULT NULL,
  `amount` decimal(11,3) DEFAULT NULL,
  `gift_sales_price` decimal(11,3) DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `line_discount_amount` decimal(11,3) DEFAULT NULL,
  `vat` decimal(8,2) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `urban` tinyint(1) DEFAULT NULL,
  `product_classification_code` varchar(20) DEFAULT NULL,
  `customer_price_group` varchar(10) DEFAULT NULL,
  `salesperson_code` varchar(20) DEFAULT NULL,
  `unit_cost` decimal(11,3) DEFAULT NULL,
  `last_direct_cost` decimal(11,3) DEFAULT NULL,
  `area` varchar(10) DEFAULT NULL,
  `product_commission_type_code` varchar(10) DEFAULT NULL,
  `amount_including_vat` decimal(8,2) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sales_invoice_lines_document_no_line_no_index` (`document_no`,`line_no`),
  KEY `sales_invoice_lines_document_no_amount_type_index` (`document_no`,`amount`,`type`),
  KEY `sales_invoice_lines_sell_to_customer_no_index` (`sell_to_customer_no`)
) ENGINE=InnoDB AUTO_INCREMENT=530380 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sales_order_headers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_type` varchar(255) NOT NULL,
  `no` varchar(20) NOT NULL,
  `sell_to_customer_no` varchar(20) DEFAULT NULL,
  `sell_to_customer_name` varchar(50) DEFAULT NULL,
  `sell_to_address` varchar(50) DEFAULT NULL,
  `sell_to_post_code` varchar(20) DEFAULT NULL,
  `sell_to_city` varchar(30) DEFAULT NULL,
  `sell_to_county` varchar(30) DEFAULT NULL,
  `sell_to_contact` varchar(50) DEFAULT NULL,
  `sell_to_contact_no` varchar(20) DEFAULT NULL,
  `document_date` date DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `external_document_no` varchar(35) DEFAULT NULL,
  `salesperson_code` varchar(20) DEFAULT NULL,
  `customer_price_group` varchar(10) DEFAULT NULL,
  `status` varchar(4) DEFAULT NULL,
  `ref_obra` varchar(50) DEFAULT NULL,
  `payment_terms_code` varchar(10) DEFAULT NULL,
  `payment_method_code` varchar(10) DEFAULT NULL,
  `invoice_type` varchar(4) DEFAULT NULL,
  `ship_to_code` varchar(10) DEFAULT NULL,
  `ship_to_name` varchar(50) DEFAULT NULL,
  `ship_to_address` varchar(50) DEFAULT NULL,
  `ship_to_post_code` varchar(20) DEFAULT NULL,
  `ship_to_city` varchar(30) DEFAULT NULL,
  `ship_to_county` varchar(30) DEFAULT NULL,
  `ship_to_country_region_code` varchar(10) DEFAULT NULL,
  `ship_to_contact` varchar(50) DEFAULT NULL,
  `zona_de_ventas` varchar(10) DEFAULT NULL,
  `num_bultos` decimal(8,2) NOT NULL DEFAULT 0.00,
  `portes` varchar(4) DEFAULT NULL,
  `pagaportes` varchar(4) DEFAULT NULL,
  `shipment_method_code` varchar(10) DEFAULT NULL,
  `shipping_agent_code` varchar(10) DEFAULT NULL,
  `package_tracking_no` varchar(30) DEFAULT NULL,
  `portes_documento` decimal(8,2) NOT NULL DEFAULT 0.00,
  `cobrar_portes` tinyint(1) DEFAULT NULL,
  `total_bultos` decimal(8,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25533 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sales_order_lines` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_type` varchar(255) NOT NULL,
  `document_no` varchar(20) NOT NULL,
  `line_no` int(11) NOT NULL,
  `sell_to_customer_no` varchar(20) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `no` varchar(20) DEFAULT NULL,
  `description` varchar(50) DEFAULT NULL,
  `unit_of_measure` varchar(10) DEFAULT NULL,
  `quantity` decimal(11,3) DEFAULT NULL,
  `unit_price` decimal(11,3) DEFAULT NULL,
  `unit_cost_lcy` decimal(11,3) DEFAULT NULL,
  `line_discount_percent` decimal(11,3) DEFAULT NULL,
  `line_discount_amount` decimal(11,3) DEFAULT NULL,
  `amount` decimal(11,3) DEFAULT NULL,
  `inv_discount_amount` decimal(11,3) DEFAULT NULL,
  `currency_code` varchar(10) DEFAULT NULL,
  `variant_code` varchar(10) DEFAULT NULL,
  `unit_of_measure_code` varchar(10) DEFAULT NULL,
  `qty_to_ship` decimal(11,3) DEFAULT NULL,
  `quantity_shipped` decimal(11,3) DEFAULT NULL,
  `qty_to_invoice` decimal(11,3) DEFAULT NULL,
  `quantity_invoiced` decimal(11,3) DEFAULT NULL,
  `line_amount` decimal(8,2) NOT NULL DEFAULT 0.00,
  `location_code` varchar(10) DEFAULT NULL,
  `qty_to_assemble_to_order` decimal(8,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sales_order_lines_document_type_document_no_line_no_index` (`document_type`,`document_no`,`line_no`)
) ENGINE=InnoDB AUTO_INCREMENT=239419 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sales_persons` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(20) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `e_mail` varchar(80) DEFAULT NULL,
  `phone_no` varchar(30) DEFAULT NULL,
  `vat_registration_no` varchar(20) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `sales_role_type` varchar(255) DEFAULT NULL,
  `supervisor_salesperson_code` varchar(10) DEFAULT NULL,
  `sales_area_code` varchar(10) DEFAULT NULL,
  `territory_code` varchar(50) DEFAULT NULL,
  `sales_hierarchy_role` varchar(255) DEFAULT NULL,
  `registration_date` date DEFAULT NULL,
  `termination_date` date DEFAULT NULL,
  `contract_number_type` varchar(255) DEFAULT NULL,
  `individual_group_mode` varchar(4) DEFAULT NULL,
  `allowance` decimal(10,2) DEFAULT NULL,
  `monthly_diet` decimal(8,2) NOT NULL DEFAULT 0.00,
  `location_modified_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sales_persons_code_index` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=9193 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `suppliers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `no` varchar(100) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `vat_registration_no` varchar(50) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5310 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;